#!/bin/bash

LOCATION=$HOME/.cache

SEARCH_ENGINES="\tDuckDuckGo,\tStartPage,磌\tWikipedia,\tArchWiki,\tGentooWiki,戮\tProtonDB,輸\tYouTube, \tWolfram Alpha"

ROFI_VALUE=$(echo -e $SEARCH_ENGINES | rofi -format 'i' -sep "," -i -theme fly-mini -l 8 -font "FontAwesome 17" -p "  " -no-custom -dmenu)

if [ ! -z $ROFI_VALUE ];
then
	SEARCH_QUERY="$(tail -n 10 $LOCATION/rofi-searches$ROFI_VALUE.txt | tac | rofi -dmenu -font "FontAwesome 17" -p "  " -i -theme fly-mini -l $(tail -n 10 $LOCATION/rofi-searches$ROFI_VALUE.txt | wc -l))"

	if [ -n "$SEARCH_QUERY" ];
	then
		if [ -z $(tail -n 10 $LOCATION/rofi-searches$ROFI_VALUE.txt | grep "^$SEARCH_QUERY$") ];
		then
			echo $SEARCH_QUERY >> $LOCATION/rofi-searches$ROFI_VALUE.txt
		fi

		case $ROFI_VALUE in
			0) ddg "$SEARCH_QUERY";;
			1) spg "$SEARCH_QUERY";;
			2) wkp "$SEARCH_QUERY";;
			3) wka "$SEARCH_QUERY";;
			4) wkg "$SEARCH_QUERY";;
			5) pdb "$SEARCH_QUERY";;
			6) ytb "$SEARCH_QUERY";;
			7) wlf "$SEARCH_QUERY";;
		esac
	fi
fi
