#!/bin/bash

POWER_OPTIONS="\tLock|\tLeave|\tRestart|襤\tShutdown"

ROFI_VALUE=$(echo -e ${POWER_OPTIONS[*]} | rofi -format 'i' -sep "|" -i -theme fly-mini -l 4 -font "FontAwesome 17" -p "  " -dmenu)

case $ROFI_VALUE in
    0) xscreensaver-command --lock;;
    1) rofi-confirm "Leave" "qtile cmd-obj -o cmd -f shutdown";;
    2) rofi-confirm "Restart" "reboot";;
    3) rofi-confirm "Shutdown" "poweroff";;
esac
