#!/bin/bash

CONFIRM_OPTIONS=" Yes| No"
CONFIRM_VALUE=$(echo -ne ${CONFIRM_OPTIONS[*]} | rofi -format 'i' -sep "|" -theme fly-dialog -p "Confirm $1 ?" -dmenu)

if [ ! -z $CONFIRM_VALUE ];
then
    if [ $CONFIRM_VALUE -eq 0 ];
    then
        eval "$2"
    else
        echo "Canceled $1"
    fi
fi
