#!/bin/bash

POWER_OPTIONS="|||襤"
ROFI_VALUE=$(echo -ne ${POWER_OPTIONS[*]} | rofi -format 'i' -sep "|" -theme fly-power -dmenu)

if [ ! -z $ROFI_VALUE ];
then
    case $ROFI_VALUE in
        0) xscreensaver-command --lock;;
        1) rofi-confirm "Leave" "qtile cmd-obj -o cmd -f shutdown";;
        2) rofi-confirm "Restart" "reboot";;
        3) rofi-confirm "Shutdown" "poweroff";;
    esac
fi

